=== EvoEpi/mauve/trunk/mauve/src/uk/ac/man/bioinf/apps/cinema/resources/module.dtd
<?xml encoding="UTF-8"?>


<!ELEMENT configuration (identifier*, module*, load*, start*, read*)>

<!-- defines a Java class. Used in several places -->
<!ELEMENT class (#PCDATA) >               

<!-- defines a module name -->
<!ELEMENT name (#PCDATA) >        
        
<!--
        Identifier:- This defines an indentifier for a module. There
        are two ways of doing this, which offer a nice comprimise
        between type safety within Java and genericity outside of it. 

        These two types are
              1) Enumeration. This is an identifier which extends
                 uk.ac.man.bioinf.util.AbstractEnumeration. This
                 should also implement ModuleIdentifier, and all the
                 elements of this class should each identify a single
                 module. Although it is not required it is recommended
                 Enumerations of this type actually extend from
                 uk.ac.man.bioinf.module.AbstractEnumeratedIdentifier.
                 This class ensures (or will do when its written!
                 PENDING:- PL) that the module name returned by an
                 object is the same as the variable name which holds
                 a reference to that object. This should ease
                 debugging.
                
              2) Generic. These are identifiers specified by the class
                 uk.ac.man.bioinf.module.GenericIdentifier, where both
                 the module name, and the class name is defined within
                 the XML. Instances of this class must be obtained
                 from the GenericIdentifier.resolveIdentifier( String )
                 within Java which at least has the advantage of being
                 fail-fast if not type safe.    
-->
<!ELEMENT identifier (enumeration|generic)>

<!--
        There are two types of modules, which are those
        defined by classes and those defined by interfaces. For those
        defined by interfaces there should also be a module which
        implements this interface, and will provide the object that is
        actually returned when the interface module is requested.
        PENDING:- PL. It would be possible to require that a concrete
        module be specified when the interface is defined but Ive
        decided not to. The idea is that you might want to define
        modules in one file and the implementation in another. 
-->
<!ATTLIST identifier  concrete (true|false) 'true'>         

<!ELEMENT enumeration (class)>
<!ELEMENT generic (class,name)>


<!-- 
        This tag is for module configuration. This bit is fairly open
        at the moment. 
-->
<!ELEMENT module (name, provide?,config)>

<!-- 
        This is a module which is providing the concrete
        implementation for an interface module. 
-->
<!ELEMENT provide (name)>


<!-- 
        This is the configuration for this module. This bit is totally
        open at the moment. Eventually it should several tags which
        map to various data structures that I might want to use as
        configuration. Also I havent worked out what to do yet for
        interfaces modules. Should I just add the configurations
        together or what?
-->     
<!ELEMENT config (properties?,tree?)>
        
<!--
        What to do with this config.
        replace - replace any existing configuration for this module
        add     - add to any existing configuration. Note that the properties
        configuration will still overwrite any other property with the same name
-->
<!ATTLIST config mode (replace|add) 'add'>


<!--
        A properties list
-->
<!ELEMENT properties (param+)>
<!ELEMENT param ((paramname, (value|name))+)>
<!ELEMENT paramname (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!--  
        A tree structure
-->
<!ELEMENT tree (node*)>
<!ELEMENT node ((value|name), node*)>
        
     
<!--  
        Actually load an instance of a module at this point
-->
<!ELEMENT load (name)>

<!--
        Start an instance of a module at this point
-->
<!ELEMENT start (name)>

<!--     
        Read another XML file. I think that this should leave fairly
        open how the file is specified, and where it is looked for.
-->     
<!ELEMENT read (#PCDATA)>

<!-- 
        If true and the file is not found then an error will be thrown, 
        otherwise it will be silently ignored
-->
<!ATTLIST read required (true|false) 'true'>

=== EvoEpi/mauve/src/uk/ac/man/bioinf/apps/cinema/resources/cinema-main.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "module.dtd">

 
<!-- This program is free software; you can redistribute it and/or modify -->
<!-- it under the terms of the GNU General Public License as published by -->
<!-- the Free Software Foundation; either version 2 of the License, or -->
<!-- (at your option) any later version. -->
    
<!-- This program is distributed in the hope that it will be useful, -->
<!-- but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the -->
<!-- GNU General Public License for more details. -->
    
<!-- You should have received a copy of the GNU General Public License -->
<!-- along with this program; if not, write to the Free Software -->
<!-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA -->


<!-- This file is loaded for every main frame of Cinema that is loaded -->
<!-- into memory. Its meant to load everything that is needed by a -->
<!-- working Cinema -->

<configuration>
   
  <!-- Loads the identifiers -->
  <read>cinema-identifiers.xml</read>

  <!-- Load support for persistance. This needs to be done fairly
  early!-->
  <module>
    <name>CINEMA_PERSIST</name>
    <provide>
      <name>CINEMA_FILE_PERSIST</name>
    </provide>
    <config>
    </config>
  </module>

  <load>
    <name>CINEMA_PERSIST</name>
  </load>
  <start>
    <name>CINEMA_PERSIST</name>
  </start>
  
  <load>
    <name>CINEMA_SYSTEM_EVENTS</name>
  </load>
  
  <!-- Loads the input and output modules -->
  <read>cinema-io.xml</read>
  
  <!-- Load the calculation modules -->
  <read>cinema-calculate.xml</read>

  <!-- Loads the viewing modules -->
  <read>cinema-view.xml</read>
  
  <!-- Loads the manipulation modules -->
  <read>cinema-manipulate.xml</read>

  <!-- read in the configuration for the menu system -->
  <read>cinema-menu.xml</read>

  <!-- load the user defined config -->
	<read required='false'>main.xml</read>
  
  <load>
    <name>CINEMA_GO</name>
  </load>
  <start>
    <name>CINEMA_GO</name>
  </start>

</configuration>

=== EvoEpi/mauve/mauve/src/uk/ac/man/bioinf/apps/cinema/resources/cinema-menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "module.dtd">



<!-- This program is free software; you can redistribute it and/or modify -->
<!-- it under the terms of the GNU General Public License as published by -->
<!-- the Free Software Foundation; either version 2 of the License, or -->
<!-- (at your option) any later version. -->
    
<!-- This program is distributed in the hope that it will be useful, -->
<!-- but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the -->
<!-- GNU General Public License for more details. -->
    
<!-- You should have received a copy of the GNU General Public License -->
<!-- along with this program; if not, write to the Free Software -->
<!-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA -->



<!-- This file configures and loads the Cinema Menu system. I have -->
<!-- placed this separately because its a fairly long and complex -->
<!-- configuration, and it just complicates the main system. -->

<configuration>
  
  <!-- Configure the menu system -->
  <module>
    <name>CINEMA_MENU_SYSTEM</name>
    <config>
      <tree>
        <!-- The File Menu -->
        <node>
          <value>File</value>
          <node>
            <!-- Provides the save alignment -->
            <name>XMFA_MODEL_OUTPUT</name>
          </node>
          <node>
            <!-- Provides the exit menu -->
            <name>CINEMA_CORE_GUI</name>
          </node>
        </node>
        <!-- End File Menu -->
        
        <!-- The Edit Menu -->
        <node>
          <value>Edit</value>
<!--TODO: Either remove permanently or restore (commented out to remove Motif stuff) -->
<!--          
          <node>
            <name>CINEMA_MOTIF</name>
          </node>
-->
          <node>
            <name>CINEMA_REGEXP</name>
          </node>
        </node>
        <!-- End View Menu -->

        <node>
          <value>View</value>
          <node>
            <!-- Provides the ability to resize the elements of the
            viewer -->
            <name>CINEMA_RESIZE_ELEMENTS</name>
	  </node>
        </node>
        
        <!-- The Colour Menu -->
        <node>
          <value>Colour</value>
          <node>
            <name>CINEMA_COLOR_SELECTOR</name>
          </node>
        </node>
        <!-- End Colour Menu -->
        
        <!-- The Group Menu -->
        <node>
          <value>Group</value>
          <node>
            <!-- Provides the group frame -->
            <name>CINEMA_GROUPS</name>
          </node>
        </node>
        <!-- End Group Menu -->

        <!-- The Consensus Menu -->
        <node>
          <value>Consensus</value>
          <node>
            <name>CINEMA_CONSENSUS_DISPLAY</name>
          </node>
        </node>
      </tree>
    </config>
  </module>
	
  
  <!-- Read the menu hook to enable addition of more configuration by
  the user -->
  <read required='false'>menu-hook.xml</read>
  
  <!-- Add in Menu system -->
  <load>
    <name>CINEMA_MENU_SYSTEM</name>
  </load>
  <start>
    <name>CINEMA_MENU_SYSTEM</name>
  </start>
  
</configuration>

=== EvoEpi/mauve/trunk/mauve/src/uk/ac/man/bioinf/apps/cinema/resources/cinema-view.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "module.dtd">


 
<!-- This program is free software; you can redistribute it and/or modify -->
<!-- it under the terms of the GNU General Public License as published by -->
<!-- the Free Software Foundation; either version 2 of the License, or -->
<!-- (at your option) any later version. -->
    
<!-- This program is distributed in the hope that it will be useful, -->
<!-- but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the -->
<!-- GNU General Public License for more details. -->
    
<!-- You should have received a copy of the GNU General Public License -->
<!-- along with this program; if not, write to the Free Software -->
<!-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA -->


<!-- This loads all of those modules which are involved with changing -->
<!-- the way that the sequence are viewed -->

<configuration>

  <!-- The color selector chooses the colours that cinema displays -->
  
  <load>
    <name>CINEMA_COLOR_SELECTOR</name>
  </load>
  
  <!-- Configuration for the colour selector module -->
  <module>
    <name>CINEMA_COLOR_FACTORY</name>
    <config>
      <properties> 
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.GrayScaleVariance</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.AminoAcidColorMapMetaData</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.PercentageIDVarianceColorMapMetaData</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.TaylorColorMapMetaData</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.ThreadedPercentageIDVarianceColorMapMetaData</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.ColormapColorMapMetaData</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.DefaultColorMapMetaData</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.IntenseColorMapMetaData</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.PedanticColorMapMetaData</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.VariableColorMapMetaData</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.VariationsColorMapMetaData</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.color.ZenecaColorMapMetaData</paramname>
          <value></value>
        </param>
      </properties>
    </config>
  </module>

  <load>
    <name>CINEMA_RESIZE_ELEMENTS</name>
  </load>
  
  <load>
    <name>XMFA_STATUS_INFORMATION</name>
  </load>
  <start>
    <name>XMFA_STATUS_INFORMATION</name>
  </start>
</configuration>

=== EvoEpi/mauve/mauve_contigs/src/uk/ac/man/bioinf/apps/cinema/resources/cinema-calculate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "module.dtd">



<!-- This program is free software; you can redistribute it and/or modify -->
<!-- it under the terms of the GNU General Public License as published by -->
<!-- the Free Software Foundation; either version 2 of the License, or -->
<!-- (at your option) any later version. -->
    
<!-- This program is distributed in the hope that it will be useful, -->
<!-- but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the -->
<!-- GNU General Public License for more details. -->
    
<!-- You should have received a copy of the GNU General Public License -->
<!-- along with this program; if not, write to the Free Software -->
<!-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA -->



<!-- There are modules that do lots of calculations to produce their -->
<!-- results. -->

<configuration>
  
  <module>
    <name>CINEMA_MULTIPLE_CONSENSUS</name>
    <config>
      <tree>
        <node>
          <value>Options</value>
          <node>
            <name>CINEMA_COLOR_SELECTOR</name>
          </node>
          <node>
            <name>CINEMA_RESIZE_ELEMENTS</name>
          </node>
        </node>
      </tree>
    </config>
  </module>
  

  <!-- Configure the consensus calculation module -->
  <module>
    <name>CINEMA_CONSENSUS</name>
    <config>
      <properties>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.consensus.PercentageIDConsensusCalculatorMetaData</paramname>
          <value></value>
        </param>
        <param>
          <paramname>uk.ac.man.bioinf.apps.cinema.consensus.ThreadedPercentageIDConsensusCalculatorMetaData</paramname>
          <value>default</value>
        </param>
      </properties>
    </config>
  </module>

  <!-- Now load the consensus display module -->
  <load>
    <name>CINEMA_CONSENSUS_DISPLAY</name>
  </load>
  <start>
    <name>CINEMA_CONSENSUS_DISPLAY</name>
  </start>
</configuration>
